version: "3.8"

name: my-server

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    environment:
      - PORT=5000
    container_name: myserver
